FROM nginx

# Копируем самоподписанный сертификат и ключ в контейнер
COPY ssl/nginx.crt /etc/nginx/ssl/nginx.crt
COPY ssl/nginx.key /etc/nginx/ssl/nginx.key

# Копируем конфигурационный файл для виртуального хоста
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 443