# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    ports:
      - "27017:27017"
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./app/webapps/trainer-form:/usr/share/nginx/html
    ports: ["8086:80"]