name: deploy
on: 
  push:
#    tags:
#      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1


      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1


      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: workout_bot
          IMAGE_TAG: $GITHUB_REF_NAME
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$GITHUB_REF_NAME .
          docker push $REGISTRY/$REPOSITORY:$GITHUB_REF_NAME
          

      - uses: hashicorp/setup-terraform@v2

      - run: terraform init
        working-directory: ./service-infra-deploy

      - run: terraform apply -auto-approve -var="BOT_TOKEN=${{ secrets.BOT_TOKEN }}" -var="AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -var="IMAGE_TAG=$GITHUB_REF_NAME" -var="MONGO_CONNECTION_STRING=${{ secrets.MONGO_CONNECTION_STRING }}"
        working-directory: ./service-infra-deploy